workflows:
  android-workflow:
    name: Android APK Build
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - cd flutter/examples/hello_world
      - flutter pub get
      - flutter build apk
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
